stages:
  - deploy

deploy_job:
  stage: deploy
  tags:
    - Ansible deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "{ip_do_server}" >> ~/.ssh/known_hosts
    - rsync -avz --delete ./ {usuario}@{ip_do_server}:/etc/ansible/
  only:
    - main


