- name: Backup MySQL Databases and Fetch to Control Machine
  hosts: db_servers
  become: true
  vars:
    backup_dir: "/var/backups/mysql"  # Diretório remoto para backups
    mysql_root_user: "{usuario}"           # Usuário do MySQL
    mysql_root_password: "{senha}" # Senha do root
    exclude_dbs:                     # Bancos a serem excluídos
      - "information_schema"
      - "performance_schema"
      - "mysql"
      - "sys"
    timestamp: "{{ ansible_date_time.iso8601 }}"  # Timestamp 
    local_backup_dir: "./mysql_backups/"          # Diretorio do server local
  tasks:
    - name: Garantir que o diretorio do backup exista
      file:
        path: "{{ backup_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: listar os bancos de dados
      shell: |
        mysql -u{{ mysql_root_user }} -p{{ mysql_root_password }} -e "SHOW DATABASES;" | grep -v Database
      register: databases
      changed_when: false

    - name: Filtrar os bancos que não precisar faze o backup
      set_fact:
        databases_to_backup: "{{ databases.stdout_lines | difference(exclude_dbs) }}"

    - name: Fazendo o backup dos bancos
      loop: "{{ databases_to_backup }}"
      loop_control:
        label: "{{ item }}"
      shell: |
        mysqldump -u{{ mysql_root_user }} -p{{ mysql_root_password }} {{ item }} > {{ backup_dir }}/{{ item }}_{{ timestamp }}.sql
      args:
        executable: /bin/bash

    - name: Enviando para o servidor de backup
      loop: "{{ databases_to_backup }}"
      loop_control:
        label: "{{ item }}"
      fetch:
        src: "{{ backup_dir }}/{{ item }}_{{ timestamp }}.sql"
        dest: "{{ local_backup_dir }}"
        flat: yes
